server:
  port: 10001
spring:
  application:
    name: news-cloud-config
  cloud:
    config:
      server:
        git:
          uri: http://git.oschina.net/didispace/config-repo-demo/
      enabled: true
management:
  security:
    enabled: false