server:
  port: 10001
spring:
  application:
    name: news-cloud-config
  cloud:
    config:
      server:
        svn:
          uri: http://10.7.21.10:81/svn/yo-news-sale/
          username: zqj
          password: zqj
          default-label: config
      enabled: true
  profiles:
    active:
    - subversion
management:
  security:
    enabled: false